version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_API_SERVICE_URL: "http://localhost:5004"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  822575900206.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo building test-driven-users image...
      - >
        docker build \
          -f services/users/Dockerfile.prod \
          -t 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:prod \
          ./services/users
      - echo building test-driven-client image...
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:prod \
          --build-arg NODE_ENV=production --build-arg REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL} \
          ./services/client
  post_build:
    commands:
      - docker push 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:prod
      - docker push 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:prod
