version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_API_SERVICE_URL: "http://flask-react-alb-1074410246.us-east-1.elb.amazonaws.com"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  822575900206.dkr.ecr.us-east-1.amazonaws.com
      - docker pull 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:prod || true
      - docker pull 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder || true
      - docker pull 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:prod || true
  build:
    commands:
      # - echo building test-driven-users image...
      # - echo building and testing dev images...
      # - docker-compose up -d --build
      # - docker-compose exec -T api python -m pytest "src/tests" -p no:warnings --cov="src"
      # - docker-compose exec -T api flake8 src
      # - docker-compose exec -T api black src --check
      # - docker-compose exec -T api isort src --check-only
      # - docker-compose exec -T client npm run lint
      # - docker-compose exec -T client npm run prettier:check
      # - docker-compose exec -T client npm run prettier:write
      - echo building prod images...
      - >
        docker build \
          -f services/users/Dockerfile.prod \
          -t 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:prod \
          ./services/users
      - echo building test-driven-client image...
      - >
        docker build \
          --target builder \
          --cache-from 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder \
          -f services/client/Dockerfile.prod \
          -t 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=$REACT_APP_API_SERVICE_URL \
          ./services/client
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:prod \
          --build-arg NODE_ENV=production --build-arg REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL} \
          ./services/client
  post_build:
    commands:
      - echo pushing prod images to ecr...
      - docker push 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-users:prod
      - docker push 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:builder
      - docker push 822575900206.dkr.ecr.us-east-1.amazonaws.com/test-driven-client:prod
